repos:
  - repo: local
    hooks:
      - id: validate-blog-tags
        name: Validate blog tags
        entry: python scripts/validate_tags.py
        language: system
        pass_filenames: false
        files: ^blog_posts/.*\.md$
