# Generated by Django 4.2.7 on 2024-05-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_image_blogpost_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='post_name',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
