# Generated by Django 4.2.7 on 2024-05-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_post_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
