# Generated by Django 4.2.7 on 2025-10-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blogpost_post_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
