# Generated by Django 4.2.7 on 2025-10-12 11:43

from django.db import migrations
from django.utils.text import slugify


def seed_tags(apps, schema_editor):
    Tag = apps.get_model("blog", "Tag")
    BlogPost = apps.get_model("blog", "BlogPost")

    default_tags = ["post", "WIP", "talk", "notes"]

    created_tags = {}
    for name in default_tags:
        slug = slugify(name).lower()
        tag, _ = Tag.objects.get_or_create(slug=slug, defaults={"name": name})
        created_tags[name.lower()] = tag

    post_tag = created_tags.get("post")
    if post_tag:
        for blog_post in BlogPost.objects.all():
            blog_post.tags.add(post_tag)


def unseed_tags(apps, schema_editor):
    Tag = apps.get_model("blog", "Tag")
    BlogPost = apps.get_model("blog", "BlogPost")

    slugs = [slugify(name).lower() for name in ["post", "WIP", "talk", "notes"]]

    tags = list(Tag.objects.filter(slug__in=slugs))

    if not tags:
        return

    for blog_post in BlogPost.objects.all():
        blog_post.tags.remove(*tags)

    Tag.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_tag_blogpost_tags"),
    ]

    operations = [
        migrations.RunPython(seed_tags, unseed_tags),
    ]
